version: "3.9"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    container_name: events-db
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432

  cache:
    image: redis
    container_name: events-cache
    ports:
      - ${REDIS_PORT}:6379

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    depends_on:
      - db
      - cache
    container_name: events-server
    env_file: .env
    ports:
     - ${SERVER_PORT}:8000

  api-docs:
    image: mrin9/rapidoc
    container_name: events-api-docs
    ports:
      - ${RAPIDOC_PORT}:80
    volumes:
      - ./schema.yml:/usr/share/nginx/html/schema.yml
    env_file: .env

volumes:
  postgres_data:
