# Generated by Django 4.1.3 on 2022-11-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('event', 'owner')},
        ),
    ]
